GET http://localhost:8003/batch/hello
Accept: application/json

###

GET http://localhost:8000/batch/hello
Accept: application/json

###



POST http://localhost:8000/batch/admin/job/run
Content-Type: application/json

{
"name": "train.batch.job.DailyTrainJob",
"jobGroupName": "default"
}